"""Initial migration.

Revision ID: 66ae612a166d
Revises: 9de92c0d146c
Create Date: 2024-03-03 16:12:56.321867

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '66ae612a166d'
down_revision = '9de92c0d146c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('servico', schema=None) as batch_op:
        batch_op.drop_column('data')
        batch_op.drop_column('status')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('servico', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.INTEGER(), nullable=False))
        batch_op.add_column(sa.Column('data', sa.DATE(), nullable=True))

    # ### end Alembic commands ###
