"""initial db

Revision ID: bdfd2a66ab53
Revises: 
Create Date: 2024-03-03 23:32:01.612344

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bdfd2a66ab53'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('carro',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('marca', sa.String(length=255), nullable=False),
    sa.Column('placa', sa.String(length=20), nullable=False),
    sa.Column('modelo', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('placa')
    )
    op.create_table('funcionario',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=255), nullable=False),
    sa.Column('funcao', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cliente',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=255), nullable=False),
    sa.Column('id_carro', sa.Integer(), nullable=True),
    sa.Column('endereco', sa.String(length=255), nullable=False),
    sa.Column('telefone', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['id_carro'], ['carro.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('servico',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('descricao', sa.String(length=255), nullable=False),
    sa.Column('id_carro', sa.Integer(), nullable=True),
    sa.Column('id_funcionario', sa.Integer(), nullable=True),
    sa.Column('data', sa.DateTime(), nullable=False),
    sa.Column('status', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_carro'], ['carro.id'], ),
    sa.ForeignKeyConstraint(['id_funcionario'], ['funcionario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('servico')
    op.drop_table('cliente')
    op.drop_table('funcionario')
    op.drop_table('carro')
    # ### end Alembic commands ###
